title: Sharaal's Blog (Archiv)
description: Yet another Blog by and for AI Enthusiasts and Developers (Archiv)
author: Sharaal
email: blog@sharaal.de
github_username: Sharaal
theme: minima
show_excerpts: true
excerpt_separator: <!--more-->
gems:
- jekyll-feed
